export default [
  [
    "Friday",
    [
      {
        description: "",
        title: "Mentor Check-In",
        startTime: "2019-04-12 17:00",
        endTime: "2019-04-12 18:00",
        location: "Xfinity Gate A",
        img: "",
        featuredEvent: false,
        eventID: 20051,
        category: ["Mentor"],
        caption: "Xfinity Gate A",
      },
      {
        description: "",
        title: "Hacker Check-In",
        startTime: "2019-04-12 17:00",
        endTime: "2019-04-12 18:00",
        location: "Xfinity Gate A",
        img: "",
        featuredEvent: false,
        eventID: 20052,
        category: ["Main"],
        caption: "Xfinity Gate A",
      },
      {
        description: "",
        title: "UMD Student Check-in",
        startTime: "2019-04-12 18:00",
        endTime: "2019-04-12 19:30",
        location: "Xfinity Gate A",
        img: "",
        featuredEvent: false,
        eventID: 20053,
        category: ["Main"],
        caption: "Welcome fellow terps!",
      },
      {
        description: "nom nom nom",
        title: "Dinner",
        startTime: "2019-04-12 18:00",
        endTime: "2019-04-12 20:00",
        location: "Food Station",
        img: "",
        featuredEvent: false,
        eventID: 20054,
        category: ["Food"],
        caption: "Serving: Sbarro",
      },
      {
        description: "",
        title: "Sponsorship Fair",
        startTime: "2019-04-12 18:00",
        endTime: "2019-04-12 20:30",
        location: "The Campfire",
        img: "",
        featuredEvent: false,
        eventID: 20055,
        category: ["Sponsor"],
        caption: "Elevator speech ready?",
      },
      {
        description: "",
        title: "Opening Ceremony",
        startTime: "2019-04-12 19:30",
        endTime: "2019-04-12 21:00",
        location: "The Campfire",
        img: "",
        featuredEvent: false,
        eventID: 20056,
        category: ["Main"],
        caption: "Cohosted by NSA",
      },
      {
        description: "",
        title: "Hacking Starts",
        startTime: "2019-04-12 21:00",
        endTime: "2019-04-12 21:00",
        location: "The Campfire",
        img: "",
        featuredEvent: false,
        eventID: 20057,
        category: ["Main"],
        caption: "You have T-36 hours",
      },
      {
        description: "",
        title: "Dessert",
        startTime: "2019-04-12 21:00",
        endTime: "2019-04-12 21:00",
        location: "The Dock",
        img: "",
        featuredEvent: false,
        eventID: 20058,
        category: ["Food"],
        caption: "Serving: Cupcakes",
      },
      {
        description:
          "Bitcamp's take on hackathon 101! This brief workshop will get you familiar with Bitcamp and the general scope of a hackathon! First time? Come out and learn the basics you'll need to get started!\n \nSkill Level: Beginner",
        title: "Bitcamp 101",
        startTime: "2019-04-12 21:00",
        endTime: "2019-04-12 21:30",
        location: "The Treehouse",
        img: "",
        featuredEvent: true,
        eventID: 20059,
        category: ["Workshop", "Main"],
        caption: "Learn the Ropes!",
      },
      {
        description:
          "In this workshop we'll give you the tools needed to add the power of location to your application with a comprehensive mapping platform. You will learn how to get started with JavaScript,Python,and native mobile SDKs,as well as discover services for finding locations,directions,demographic data,ready-to-use basemaps and feature data that you can store on our cloud platform.\n \nSkill Level: Beginner to Advanced",
        title: "Amp Up Your Apps with Maps",
        startTime: "2019-04-12 21:00",
        endTime: "2019-04-12 22:00",
        location: "The Cabin",
        img: "",
        featuredEvent: true,
        eventID: 20060,
        category: ["Workshop", "Sponsor"],
        caption: "By Esri",
      },
      {
        description: "",
        title: "Team Formation",
        startTime: "2019-04-12 21:30",
        endTime: "2019-04-12 22:00",
        location: "The Treehouse",
        img: "",
        featuredEvent: true,
        eventID: 20061,
        category: ["Main"],
        caption: "Meet your future BFFs",
      },
      {
        description:
          "Still have questions about what Bitcamp 2019's Compass Challenge is all about? Come to our panel put on by Bitcamp organizers and prepare to create the greatest social hacks the world has ever seen.\n \nSkill Level: Everyone",
        title: "Compass Challenge Panel",
        startTime: "2019-04-12 22:00",
        endTime: "2019-04-12 23:00",
        location: "The Treehouse",
        img: "",
        featuredEvent: true,
        eventID: 20062,
        category: ["Workshop", "Main"],
        caption: "How to Win Bitcamp: 101",
      },
      {
        description:
          "Come and learn how to make your first hardware hack. We will cover the basics of Arduino and attempt to make a small robot.\n \nSkill Level: Some coding experience is recommended but even a novice hackers should be able to follow along.",
        title: "Intro to Hardware",
        startTime: "2019-04-12 22:00",
        endTime: "2019-04-12 23:00",
        location: "The Cabin",
        img: "",
        featuredEvent: false,
        eventID: 20063,
        category: ["Workshop", "Mentor"],
        caption: "CE for non-CE",
      },
      {
        description:
          "In this workshop,you will learn how to host your application on Google Cloud Platform (GCP) and the benefits of using Cloud Computing. This workshop is aimed towards beginners,and no prior coding experience is required.\n \nSkill Level: Beginner",
        title: "Cloud 101",
        startTime: "2019-04-12 22:00",
        endTime: "2019-04-12 23:00",
        location: "The Observatory",
        img: "",
        featuredEvent: false,
        eventID: 20064,
        category: ["Workshop", "Mentor"],
        caption: "Fake Meteorology",
      },
      {
        description:
          "This workshop will cover the basics for wiring and programming the wearable-friendly ATTiny85 MPU through the Arduino IDE. We will be building a simple light-detection circuit and cover topics in wearable design such as physical and programmatic techniques for battery conservation and electrical safety considerations in wearable design. There will be circuit supplies and an ATTiny85 MPU provided during the workshop.\n \nSkill Level: Intermediate",
        title: "Introduction to ATTiny and \nWearable Design",
        startTime: "2019-04-12 23:00",
        endTime: "2019-04-13 00:00",
        location: "The Cabin",
        img: "",
        featuredEvent: false,
        eventID: 20065,
        category: ["Workshop", "Mentor"],
        caption: "Bling Bling",
      },
      {
        description:
          "Learn the basics of rocking a technical interview with the instructors of CMSC389O: The Coding Interview! This workshop is geared towards students who have little to no interview experience but will provide useful tips and tricks for more veteran interviewees as well. \n \nSkill Level: Everyone",
        title: "Rocking the Coding Interview",
        startTime: "2019-04-12 23:00",
        endTime: "2019-04-13 00:00",
        location: "The Treehouse",
        img: "",
        featuredEvent: false,
        eventID: 20066,
        category: ["Workshop", "Mentor"],
        caption: "Algorithms 101",
      },
    ],
  ],
  [
    "Saturday",
    [
      {
        description: "",
        title: "Hungry Hungry Hippos",
        startTime: "2019-04-13 00:00",
        endTime: "2019-04-13 01:00",
        location: "The Cabin",
        img: "",
        featuredEvent: false,
        eventID: 20067,
        category: ["Mini"],
        caption: "Human Sized",
      },
      {
        description: "",
        title: "Smash Tournament",
        startTime: "2019-04-13 00:00",
        endTime: "2019-04-13 02:00",
        location: "The Campfire",
        img: "",
        featuredEvent: true,
        eventID: 20068,
        category: ["Sponsor", "Mini"],
        caption: "By Capital One",
      },
      {
        description: "nom nom nom",
        title: "Breakfast",
        startTime: "2019-04-13 08:30",
        endTime: "2019-04-13 10:00",
        location: "Food Station",
        img: "",
        featuredEvent: false,
        eventID: 20069,
        category: ["Food"],
        caption: "Serving: UMD Dining",
      },
      {
        description:
          "The Unity Engine is a powerful tool of developing interactive digital experiences like games,simulations,etc. without having to start from scratch. Unity provides a visual interface and software framework that makes building immersive,sophisticated experiences easy. In this workshop we'll cover the basics of getting up and running with Unity,and explore some of its most powerful features.\n \nSkill Level: Beginner!",
        title: "Introduction to Unity",
        startTime: "2019-04-13 10:00",
        endTime: "2019-04-13 11:00",
        location: "The Treehouse",
        img: "",
        featuredEvent: false,
        eventID: 20070,
        category: ["Workshop", "Mentor"],
        caption: "Make your own Game in 3,2,1",
      },
      {
        description:
          "Have you ever wondered how much network traffic your phone generates? Have you tried to capture and understand traffic in a network but been completely overwhelmed? This presentation addresses these issues and more! Through visualizing network communications in real time,patterns tend to emerge far easier than staring at Netflows and packet captures. This talk will introduce basic computer networking topics with simple examples and will provide a visual understanding of how different networking technologies affect a network at scale.\n \nSkill Level: Everyone!",
        title: "Real Time Network Visualization",
        startTime: "2019-04-13 10:00",
        endTime: "2019-04-13 11:00",
        location: "The Cabin",
        img: "",
        featuredEvent: true,
        eventID: 20071,
        category: ["Workshop", "Mentor"],
        caption: "By NSA",
      },
      {
        description: "",
        title: "Mural Unveiling",
        startTime: "2019-04-13 10:30",
        endTime: "2019-04-13 10:30",
        location: "The Campfire",
        img: "",
        featuredEvent: false,
        eventID: 20072,
        category: ["Main"],
        caption: "Happy Little Campfires",
      },
      {
        description:
          "Ask Me Anything with attorney mentor on hand to answer any of your questions.\n \nSkill Level: Everyone!",
        title: "Attorney AMA: Open Forum",
        startTime: "2019-04-13 11:00",
        endTime: "2019-04-13 12:00",
        location: "The Campfire",
        img: "",
        featuredEvent: false,
        eventID: 20073,
        category: ["Workshop", "Mentor"],
        caption: "LIT-igation and Appeals",
      },
      {
        description:
          "The interactive workshop will provide an introduction to machine learning (ML) and how it works. A subset of Artificial Intelligence, ML is gaining momentum just about everywhere! Learn about ML applications, tips critical to its success, and models and how they are trained. Participants will receive an optional hands-on exercise to train a simple, yet surprisingly accurate, ML model to recognize hand-written digits.\n \nSkill Level: Everyone!",
        title: "Explore Machine Learning - A Crash Course!",
        startTime: "2019-04-13 11:00",
        endTime: "2019-04-13 12:00",
        location: "The Cabin",
        img: "",
        featuredEvent: true,
        eventID: 20074,
        category: ["Workshop", "Sponsor"],
        caption: "By FINRA",
      },
      {
        description: "nom nom nom",
        title: "Lunch",
        startTime: "2019-04-13 12:30",
        endTime: "2019-04-13 14:00",
        location: "Food Station",
        img: "",
        featuredEvent: false,
        eventID: 20075,
        category: ["Food"],
        caption: "Serving: Sbarro/Taco Bell",
      },
      {
        description:
          "The purpose of the Workshop is to provide an overview of how organizations should think about the difficult task of managing cybersecurity risk as a dynamic process that includes several different factors. Although some of the key factors in managing cybersecurity risk are related to computer science and engineering, other factors are more closely related to economics and accounting. One such example of the latter concerns, which will be emphasized during the Workshop, is determining the appropriate level of investment in cybersecurity activities.\n \nSkill Level: Everyone!",
        title: "Risk Management in CyberSpace",
        startTime: "2019-04-13 14:00",
        endTime: "2019-04-13 14:30",
        location: "The Observatory",
        img: "",
        featuredEvent: false,
        eventID: 20076,
        category: ["Workshop", "Mentor"],
        caption: "Battle Against Cyberattacks",
      },
      {
        description:
          "What is your cause? How can you optimize your impact,regardless of your skill set or background? Come learn about how to use technology and the law as tools to affect social change. Explore the science and technology nonprofit scene,find how nonprofits are leveraging technology,and discover how the legal framework moves the needle on social issues. Hear from a panel of professionals on how they build their careers to make the world they want to see.\n \nSkill Level: Everyone!",
        title: "Attorney AMA: Tech,Law,and Social Change",
        startTime: "2019-04-13 14:00",
        endTime: "2019-04-13 15:00",
        location: "The Treehouse",
        img: "",
        featuredEvent: false,
        eventID: 20077,
        category: ["Workshop", "Mentor"],
        caption: "Making change byte by byte",
      },
      {
        description:
          "We'll be designing and styling a web application for managing todos. Starting from scratch,we'll consider all the necessary components and design the layout of the application,then build a prototype of it in HTML. Finally,we'll learn enough CSS to make the application look beautiful.\n \nSkill Level: Beginners without any web or programming knowledge",
        title: "Designing a Web Application",
        startTime: "2019-04-13 14:00",
        endTime: "2019-04-13 15:00",
        location: "The Cabin",
        img: "",
        featuredEvent: false,
        eventID: 20078,
        category: ["Workshop", "Mentor"],
        caption: "Say Goodbye to Wordpress",
      },
      {
        description: "",
        title: "Travel Reimbursements",
        startTime: "2019-04-13 14:30",
        endTime: "2019-04-13 15:30",
        location: "Bitcamp Help Desk",
        img: "",
        featuredEvent: false,
        eventID: 20079,
        category: ["Main"],
        caption: "Get your money back!",
      },
      {
        description:
          "This talk will introduce the open source Ghidra software reverse engineering (SRE) framework. NSA has applied Ghidra SRE capabilities to a variety of problems that involve analyzing malicious code and generating deep insights for SRE analysts who seek a better understanding of potential vulnerabilities in networks and systems. In this talk we will introduce Ghidra and provide a live demonstration of its binary analysis and decompilation features. You can learn more at https://ghidra-sre.org/.\n \nSkill Level: Everyone!",
        title: "Ghidra Software Reverse Engineering Framework",
        startTime: "2019-04-13 15:00",
        endTime: "2019-04-13 16:00",
        location: "The Cabin",
        img: "",
        featuredEvent: true,
        eventID: 20080,
        category: ["Workshop", "Sponsor"],
        caption: "By NSA",
      },
      {
        description:
          "This panel will host a wide selection of UMD's various on-campus organizations. If you enjoyed the spirit and community of Bitcampl, please check out all these other amazing ways you can get involved with Computer Science and Engineering clubs!\n \nSkill Level: Everyone",
        title: "UMD Organizations Panel",
        startTime: "2019-04-13 15:00",
        endTime: "2019-04-13 16:00",
        location: "The Treehouse",
        img: "",
        featuredEvent: false,
        eventID: 20081,
        category: ["Workshop", "Mentor"],
        caption: "Bring fearless opinions",
      },
      {
        description:
          "This panel will host current students at the University of Maryland and will allow high schoolers to ask questions to get a better idea of the college life. Questions can be about majors, Greek life, food, etc! Come with questions and meet these great UMD students!\n \nSkill Level: High Schoolers!",
        title: "High Schooler's Panel",
        startTime: "2019-04-13 16:00",
        endTime: "2019-04-13 17:00",
        location: "The Observatory",
        img: "",
        featuredEvent: false,
        eventID: 20082,
        category: ["Workshop", "Mentor"],
        caption: "Beyond the Grad Gown",
      },
      {
        description:
          "Come hang out with TCS, the #2 Recruiter of IT services talent in the United States for some fun and games. Come over and play some fun games to mix it up and move around during the around during the event. There will be give aways for those who show up!\n \nSkill Level: Beginner",
        title: "TCS Game of Games",
        startTime: "2019-04-13 16:00",
        endTime: "2019-04-13 17:00",
        location: "The Cabin",
        img: "",
        featuredEvent: true,
        eventID: 20083,
        category: ["Workshop", "Sponsor"],
        caption: "By TCS",
      },
      {
        description:
          "We will be showcasing several useful features of Mathematica. Mathematica has powerful tools for computation,calculus,graphics,graph theory,machine learning,data processing,parallel computing,and virtually any other mathematical need. The first session will be to showcase Comp Sci tools,and the second will be to showcase introductory to advanced Mathematics tools. \n \nSkill Level: None! There will be something for everyone! We will show tools for students knowing no more than calculus,as well as advanced mathematical tools. Specifically,the Computer Scientists' Session will focus on comp sci tools,and the Mathematicians' Section will focus on advanced math tools.",
        title: "Making Everything Easier Using Mathematica",
        startTime: "2019-04-13 16:00",
        endTime: "2019-04-13 17:30",
        location: "The Treehouse",
        img: "",
        featuredEvent: false,
        eventID: 20084,
        category: ["Workshop", "Mentor"],
        caption: "Mathematicians' Session",
      },
      {
        description: "",
        title: "COLORWAR",
        startTime: "2019-04-13 16:00",
        endTime: "2019-04-13 18:00",
        location: "The Campfire",
        img: "",
        featuredEvent: true,
        eventID: 20085,
        category: ["Main"],
        caption: "Rapid-fire! Live-design!",
      },
      {
        description:
          "In this workshop,we will discuss the deployment and management of serverless mobile and web applications using Google's Firebase development platform. We will provide an in-depth overview of the powerful suite of services and have a live coding workshop so you can immediately integrate your application to the platform using Firebase Authentication.\n\nIn partnership with Google,we are holding a Spring Flash Raffle for Bitcamp participants! The winner of the raffle will receive a special package from Google,including a Google Home Mini,as well as a Google Cloud Platform t-shirt,lanyard,pin,and sticker. If you would like to be entered in the raffle,as well as receive a free $100 credit for Google Cloud Platform,please check in for the workshop here: https://ter.ps/gcpraffle\n Skill Level: Basic to intermediateLevel: Basic to intermediate",
        title: "Building Serverless Apps using Firebase",
        startTime: "2019-04-13 17:00",
        endTime: "2019-04-13 18:00",
        location: "The Cabin",
        img: "",
        featuredEvent: false,
        eventID: 20086,
        category: ["Workshop", "Mentor"],
        caption: "No Hassle Backend",
      },
      {
        description:
          "Learn the basic of Adobe Illustrator and Photoshop to create awesome graphics to your projects! We'll go over how to make simple illustrations in Illustrator, and then bring it into photoshop and learn some post-processing techniques.\n \nSkill Level: Beginner",
        title: "Intro to Illustator and Photoshop",
        startTime: "2019-04-13 17:00",
        endTime: "2019-04-13 18:00",
        location: "The Observatory",
        img: "",
        featuredEvent: true,
        eventID: 20087,
        category: ["Workshop", "Mentor"],
        caption: "Now you can always be photogenic",
      },
      {
        description: "nom nom nom",
        title: "Dinner",
        startTime: "2019-04-13 18:00",
        endTime: "2019-04-13 20:00",
        location: "Food Station",
        img: "",
        featuredEvent: false,
        eventID: 20088,
        category: ["Food"],
        caption: "Serving: Chick Fil A",
      },
      {
        description: "",
        title: "Cup Stacking",
        startTime: "2019-04-13 19:30",
        endTime: "2019-04-13 20:30",
        location: "The Campfire",
        img: "",
        featuredEvent: false,
        eventID: 20089,
        category: ["Mini"],
        caption: "Major League Hacking",
      },
      {
        description:
          "Given a non-functioning prototype of a todo web application,we will make it actually work! This will involve using the Elm programming language to build functionality in a clean and reliable way.\n \nSkill Level: Beginning programming knowledge (not necessarily any web programming) highly recommended",
        title: "Programming a Web Application",
        startTime: "2019-04-13 20:00",
        endTime: "2019-04-13 21:00",
        location: "The Cabin",
        img: "",
        featuredEvent: false,
        eventID: 20090,
        category: ["Workshop", "Mentor"],
        caption: "Software via Web",
      },
      {
        description:
          "Need any help reviewing over the various linear sorting algorithms? Does Quick Sort still stump you? Come join the Algorithms review class held by CMSC351 Tas and take a break from your project to prepare for the next exam.\n \nSkill Level: Intermediate",
        title: "Algorithms Review (CMSC351)",
        startTime: "2019-04-13 20:00",
        endTime: "2019-04-13 21:00",
        location: "The Treehouse",
        img: "",
        featuredEvent: false,
        eventID: 20091,
        category: ["Workshop", "Mentor"],
        caption: "Sorting algorithms, anyone?",
      },
      {
        description: "",
        title: "Zumba",
        startTime: "2019-04-13 21:00",
        endTime: "2019-04-13 22:00",
        location: "The Campfire",
        img: "",
        featuredEvent: false,
        eventID: 20092,
        category: ["Mini"],
        caption: "Get your groove on!",
      },
      {
        description:
          "Description: A broad introduction to using the AR Foundations package in the Unity engine for building powerful cross platform AR apps with ease.\n \nSkill Level: Anyone with basic Unity skills,Unity fundamentals will not be covered ",
        title: "Mobile Augmented Reality Development with Unity",
        startTime: "2019-04-13 21:00",
        endTime: "2019-04-13 22:00",
        location: "The Treehouse",
        img: "",
        featuredEvent: false,
        eventID: 20093,
        category: ["Workshop", "Mentor"],
        caption: "AR without a Hololens",
      },
      {
        description:
          "Learn how to pitch your project during demos and win Bitcamp's challenges,taught by a team of student investors!\n \nSkill Level: Everyone",
        title: "How to Pitch Your Project",
        startTime: "2019-04-13 21:30",
        endTime: "2019-04-13 22:00",
        location: "The Cabin",
        img: "",
        featuredEvent: false,
        eventID: 20094,
        category: ["Workshop", "Mentor"],
        caption: "Pressed to impress",
      },
      {
        description:
          "Still having trouble figuring out the Devpost website to submit your project? Come in with your questions and our Devpost experts will make sure you're on track for the Expos!\n \nSkill Level: Beginner",
        title: "Devpost Office Hours",
        startTime: "2019-04-13 22:00",
        endTime: "2019-04-13 22:30",
        location: "The Observatory",
        img: "",
        featuredEvent: false,
        eventID: 20095,
        category: ["Workshop", "Mentor"],
        caption: "First time submitting?",
      },
      {
        description:
          "An introduction to machine learning using Python using Scikit-Learn. By the end of the workshop,you will learn the basics of machine learning and be able to incorporate it into your hacks.\n \nSkill Level: Everyone",
        title: "Making Your Hacks Learn",
        startTime: "2019-04-13 22:00",
        endTime: "2019-04-13 23:00",
        location: "The Cabin",
        img: "",
        featuredEvent: false,
        eventID: 20096,
        category: ["Workshop", "Mentor"],
        caption: "Just Add ML!",
      },
      {
        description:
          "We will be doing a short demo on using Processing. We will show how to make a sketch using some of the fundamental functions in Processing,and also explain what generative art is and how you can code creatively.\n \nSkill Level: Beginner",
        title: "Intro to Generative Art with Processing",
        startTime: "2019-04-13 23:00",
        endTime: "2019-04-14 00:00",
        location: "The Cabin",
        img: "",
        featuredEvent: false,
        eventID: 20097,
        category: ["Workshop", "Mentor"],
        caption: "Art with Code",
      },
      {
        description: "",
        title: "Bot Jousting: Build Phase",
        startTime: "2019-04-13 12:00",
        endTime: "2019-04-13 14:00",
        location: "Campfire",
        img: "",
        featuredEvent: false,
        eventID: 20107,
        category: ["Mini"],
        caption: "The battle is building!",
      },
      {
        description: "",
        title: "Bot Jousting Tournament",
        startTime: "2019-04-13 14:00",
        endTime: "2019-04-13 15:00",
        location: "Campfire",
        img: "",
        featuredEvent: true,
        eventID: 20108,
        category: ["Mini"],
        caption: "Choose your fighter",
      },
    ],
  ],
  [
    "Sunday",
    [
      {
        description: "",
        title: "Movie Night",
        startTime: "2019-04-14 00:00",
        endTime: "2019-04-14 02:00",
        location: "The Cabin",
        img: "",
        featuredEvent: false,
        eventID: 20098,
        category: ["Mini"],
        caption: "Get cozy with S'mores",
      },
      {
        description: "",
        title: "S'mores",
        startTime: "2019-04-14 00:00",
        endTime: "2019-04-14 03:00",
        location: "The Dock",
        img: "",
        featuredEvent: false,
        eventID: 20099,
        category: ["Food"],
        caption: "Ooey gooey goodness",
      },
      {
        description: "",
        title: "Devpost Submission Deadline",
        startTime: "2019-04-14 08:00",
        endTime: "2019-04-14 08:00",
        location: "The Campfire",
        img: "",
        featuredEvent: false,
        eventID: 20100,
        category: ["Main"],
        caption: "It's the FINAL countdown",
      },
      {
        description: "",
        title: "Breakfast",
        startTime: "2019-04-14 08:00",
        endTime: "2019-04-14 10:00",
        location: "Food Station",
        img: "",
        featuredEvent: false,
        eventID: 20101,
        category: ["Food"],
        caption: "Serving: UMD Dining",
      },
      {
        description: "",
        title: "Hacking Ends",
        startTime: "2019-04-14 09:00",
        endTime: "2019-04-14 09:00",
        location: "The Campfire",
        img: "",
        featuredEvent: false,
        eventID: 20102,
        category: ["Main"],
        caption: "That's a wrap",
      },
      {
        description: "",
        title: "Expo A",
        startTime: "2019-04-14 09:30",
        endTime: "2019-04-14 10:30",
        location: "The Campfire",
        img: "",
        featuredEvent: false,
        eventID: 20103,
        category: ["Main"],
        caption: "Show time!",
      },
      {
        description: "",
        title: "Expo B",
        startTime: "2019-04-14 11:00",
        endTime: "2019-04-14 12:00",
        location: "The Campfire",
        img: "",
        featuredEvent: false,
        eventID: 20104,
        category: ["Main"],
        caption: "Encore!",
      },
      {
        description: "nom nom nom",
        title: "Lunch",
        startTime: "2019-04-14 12:00",
        endTime: "2019-04-14 13:00",
        location: "Food Station",
        img: "",
        featuredEvent: false,
        eventID: 20105,
        category: ["Food"],
        caption: "Serving: Subway",
      },
      {
        description: "",
        title: "Closing Ceremony",
        startTime: "2019-04-14 13:00",
        endTime: "2019-04-14 15:00",
        location: "The Campfire",
        img: "",
        featuredEvent: false,
        eventID: 20106,
        category: ["Main"],
        caption: "See you next year!",
      },
    ],
  ],
];
